# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gold', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='users_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to='multi_gold.User'),
        ),
    ]
